// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {core} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetLogs():Promise<string>;

export function GetStatus():Promise<core.ConnectionStatus>;

export function SaveConfig(arg1:config.Config):Promise<void>;
